---
version: "2"
ratings:
  paths:
  - "src/**.js"
plugins:
  eslint:
    enabled: true
    config:
      config: ./package.json
  duplication:
    enabled: false
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - javascript
  fixme:
    enabled: true
checks:
  method-lines:
    config:
      threshold: 50
