---
version: '2'
ratings:
  paths:
    - 'src/**.js'
plugins:
  eslint:
    enabled: true
    config:
      config: ./.eslintrc.yaml
  duplication:
    enabled: false
    checks:
      Similar code:
        enabled: false
    config:
      languages:
        - javascript
  fixme:
    enabled: true
checks:
  method-lines:
    config:
      threshold: 50
