root: true
extends: '@wfcd/eslint-config/esm'
parser: '@babel/eslint-parser'
parserOptions:
  sourceType: module
  ecmaVersion: 6
  ecmaFeatures:
    modules: true
rules:
  no-underscore-dangle: 'off'
  no-restricted-syntax: 'off'
  import/no-named-as-default-member: 'off'
