exit: true
spec: src/test/**/*.spec.ts
exclude: src/test/**/*-integration.spec.ts
node-option:
  - import=tsx
enableSourceMaps: true
enable-source-maps: true
checkLeaks: true
timeout: 120000
normal: 500
slow: 2000
fullTrace: true
bail: false
parallel: false
require:
  - src/test/env-setup.ts
  - src/test/hooks/setup.hook.ts
